### ISSUE TITLE
Allow Account deletion from App (Apple App store requirement)

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#72]
# Tasks
- [x] Delete account button in Settings _(in develop)_
- [x] Dialog/page(s) to confirm that the user wants to delete their account _(needs design)_
- [ ] Endpoint in backend AnalogIO/analog-core#68

## Why it's important

Apple enforces new requirements for apps per June 30. It must be possible for users to delete their account from the app

> **Account deletion within apps**
> App Store Review Guideline 5.1.1 provides people with greater control over their personal data by stating that all apps that allow for account creation must also allow users to initiate deletion of their account from within the app. This requirement was set to apply to all app submissions by January 31, 2022. Due to the complexity of implementing this requirement, we’ve extended the deadline to June 30, 2022 to give you more time.
>Please keep these requirements in mind when updating your app:
> The account deletion option should be easy to find in your app.
> - It’s insufficient to only provide the ability to temporarily disable or deactivate an account. People should be able to delete the account along with their personal data.
> - Apps in highly-regulated industries may need to provide additional support flows to confirm and facilitate the account deletion process.
> - Follow applicable legal requirements for storing and retaining user account information. This includes complying with local laws in different countries or regions. As always, check with your legal counsel.

**Comment by jonasanker** [comment]
@jonasanker Add backend story
